name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x,21.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version }}
      uses: actions/setup-node@v3
      with: 
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm install --save-dev sequelize-cli
    - run: npm ci --if-present
    - run: npm run build --if-present
    - run: npm test

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_NAME: lucaskrispim/15042024:latest
      run: |
        docker build -t $DOCKER_IMAGE_NAME
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push $DOCKER_IMAGE_NAME
        
    - name: Trigger deployment
      run: curl -X POST ${{secrets.TRIGGER_URL }}
